isDebug: true
mysql:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vote_trump?createDatabaseIfNotExist=true&&serverTimezone=Asia/Shanghai&&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&useSSL=false
    username: root
    password: sinoval@2022
    connection-timeout: 30000

spring:
    redis:
        host: localhost
        port: 6379
        password: sinoval@2022 # 如果 Redis 没有密码，可以省略
        database: 0 # 使用的数据库索引，默认是0

storage:
    minio:
        enabled: true
        url: 'https://oss.cinaval.com:9002'
        accessKey: "AINE9CHPPUPPHINNKV5Y"
        secretKey: "XOzpH2JGQl+NznwQtm6++p4UpO+7yEL2bnlC2kb+"
        secure: false
        bucketName: "bucket01"
        metricName: "minio.storage"
        checkBucket: true
        createBucket: true
    allowed:
        mime-types:
            - image/jpg
            - image/jpeg
            - image/gif
            - image/png
            - video/mp4
            - text/plain
        file-size: 20 #200MB

app:
    domainName: https://www.vote-trump.org
    port: 443