server:
  tomcat:
    accesslog:
      enabled: true
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
  #spring工程优雅停机， 非kill -9方式处理
  shutdown: graceful
  port: 8080

mybatis:
  mapper-locations: classpath:mappers/*.xml

spring:
  profiles:
    active: dev
  application:
    name: vote-trump