server:
    tomcat:
        accesslog:
            enabled: true
        uri-encoding: UTF-8
    servlet:
        encoding:
            charset: UTF-8
        context-path: /
    #spring工程优雅停机， 非kill -9方式处理
    shutdown: graceful
    port: 8443
    ssl:
        enabled: true
        key-store: classpath:ssl/keystore.jks
        key-store-password: bbcchinese
        key-store-type: JKS


mybatis:
    mapper-locations: classpath:mappers/*.xml

spring:
    profiles:
        active: dev
    application:
        name: vote-trump
    thymeleaf:
        cache: false
        encoding: utf-8
debug: true
