isDebug: false
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vote_trump?createDatabaseIfNotExist=true&&serverTimezone=Asia/Shanghai&&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&useSSL=false
    username: root
    password: sinoval@2022
    connection-timeout: 30000
  
  redis:
    host: localhost
    port: 6379
    password: proaim@2019
    database: 0
    
app:
    domain-name: https://www.votetrump.org
    port: 443